Parameters:
  Instancesize:
    Description: Instance Size
    Type: Number
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  
  EnvironmentSize:
    Description: Environment Size
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE

Mappings:
  EnvSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.small"
      "DB": "db.t2.small"
    LARGE:
      "EC2": "t2.medium"
      "DB": "db2.t2.medium"
  
  RegionMap:
    us-east-1:
      "AMA": "ami-xzysxxx"
      "Ubuntu":"ami-xzyzzzs"
    ap-southeast-2:
      "AMA": "ami-xzysxxx"
      "Ubuntu":"ami-xzyzzzs"
    


Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: '5'
      StorageType: gp2
      DBInstanceClass: !FindInMap [EnvSize, !Ref EnvironmentSize, DB]
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: w0rdpr355
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap[ RegionMap, !Ref AWS::Region , AMA] 
      InstanceType: !FindInMap [EnvSize, !Ref EnvironmentSize, EC2]
  S3:
    Type: "AWS::S3::Bucket"
    # Properties:
    #   BucketName: wp-272hhsjsjw # replace xxxxxx with random
